"""Internal helper."""

from glyphmemory.memory.competitors import (
    MIN_PAIR_OBSERVATIONS,
    NEGATIVES_PER_CHARACTER,
    CompetitorGraph,
    accumulate_occurrences,
    build_competitor_graph,
)
from glyphmemory.memory.compiler import (
    FEATURE_ATTRIBUTES,
    PROJECTED_FEATURE_LAYERS,
    compile_profile,
)
from glyphmemory.memory.fusion import blank_emission_gate, correction, fuse, personalize
from glyphmemory.memory.glyph_regions import (
    CROP_WIDTH,
    EDGE_HALF_FRAMES,
    aligned_centers,
    crops_from_occurrences,
    crops_from_spans,
    emitted_centers,
    extract_crops,
    midpoint_cells,
    region_statistics,
)
from glyphmemory.memory.pooling import POOLING_STRATEGIES, peak_frame, posterior_weighted, uniform
from glyphmemory.memory.profile import (
    PROFILE_SCHEMA_VERSION,
    Glyph,
    ProfileCompatibilityError,
    WriterProfile,
)
from glyphmemory.memory.projection import (
    DEFAULT_HIDDEN_DIM,
    DEFAULT_INPUT_DIM,
    DEFAULT_OUTPUT_DIM,
    PROJECTION_SCHEMA_VERSION,
    GlyphProjection,
    ProjectionCompatibilityError,
    ProjectionMeta,
    load_projection,
    save_projection,
)
from glyphmemory.memory.projection_training import (
    ConfusionPairs,
    OccurrenceIndex,
    TrainingLog,
    TripletBatch,
    confusion_pairs_from_top_confusions,
    cosine_triplet_loss,
    sample_triplet_batch,
    train_projection,
)
from glyphmemory.memory.prototypes import (
    DEFAULT_TOP_K,
    PROTOTYPE_STRATEGIES,
    GlyphAccumulator,
    PrototypeAccumulator,
)
from glyphmemory.memory.retrieval import memory_scores
from glyphmemory.memory.style import (
    base_style,
    batchnorm_modules,
    blend_style,
    compile_global_style,
    describe_style,
    style_bytes,
    style_dimension,
    writer_style,
)
from glyphmemory.memory.verifier import (
    DEFAULT_EMBED,
    DEFAULT_EXPANSION,
    DEFAULT_WIDTH,
    TEMPERATURE,
    GlyphVerifier,
    char_loss,
    compile_character_embeddings,
    score_candidates,
    writer_loss,
)

__all__ = [
    "CROP_WIDTH",
    "DEFAULT_EMBED",
    "DEFAULT_EXPANSION",
    "DEFAULT_HIDDEN_DIM",
    "DEFAULT_INPUT_DIM",
    "DEFAULT_OUTPUT_DIM",
    "DEFAULT_TOP_K",
    "DEFAULT_WIDTH",
    "EDGE_HALF_FRAMES",
    "FEATURE_ATTRIBUTES",
    "MIN_PAIR_OBSERVATIONS",
    "NEGATIVES_PER_CHARACTER",
    "POOLING_STRATEGIES",
    "PROFILE_SCHEMA_VERSION",
    "PROJECTED_FEATURE_LAYERS",
    "PROJECTION_SCHEMA_VERSION",
    "PROTOTYPE_STRATEGIES",
    "TEMPERATURE",
    "CompetitorGraph",
    "ConfusionPairs",
    "Glyph",
    "GlyphAccumulator",
    "GlyphProjection",
    "GlyphVerifier",
    "OccurrenceIndex",
    "ProfileCompatibilityError",
    "ProjectionCompatibilityError",
    "ProjectionMeta",
    "PrototypeAccumulator",
    "TrainingLog",
    "TripletBatch",
    "WriterProfile",
    "accumulate_occurrences",
    "aligned_centers",
    "base_style",
    "batchnorm_modules",
    "blank_emission_gate",
    "blend_style",
    "build_competitor_graph",
    "char_loss",
    "compile_character_embeddings",
    "compile_global_style",
    "compile_profile",
    "confusion_pairs_from_top_confusions",
    "correction",
    "cosine_triplet_loss",
    "crops_from_occurrences",
    "crops_from_spans",
    "describe_style",
    "emitted_centers",
    "extract_crops",
    "fuse",
    "load_projection",
    "memory_scores",
    "midpoint_cells",
    "peak_frame",
    "personalize",
    "posterior_weighted",
    "region_statistics",
    "sample_triplet_batch",
    "save_projection",
    "score_candidates",
    "style_bytes",
    "style_dimension",
    "train_projection",
    "uniform",
    "writer_loss",
    "writer_style",
]
